export type UiLocale = 'zh' | 'en';

export const UI_TEXT = {
  zh: {
    stepLabels: ['导入照片', '确认分组', '上传处理', '处理完成'] as const,
    demoStepLabels: ['导入照片', '确认分组', '上传处理', '开始处理'] as const,
    stepHints: ['导入照片并生成本地预览。', '确认自动分组是否正确。', '上传照片并开始处理。', '处理完成后直接在线查看和排序。'] as const,
    scene: { interior: '室内', exterior: '室外', pending: '待确认' } as const,
    colorMode: { default: '默认色彩', replace: '替换颜色' } as const,
    status: {
      completed: '已完成',
      processing: '处理中',
      uploading: '上传处理中',
      review: '确认分组',
      importing: '正在加载图像',
      failed: '处理失败'
    } as const,
    connectionFailed: '连接服务失败，请刷新页面后重试。',
    googleConfiguredMissing: 'Google 登录尚未配置环境变量。',
    googleOauthStateFailed: 'Google 登录校验失败，请重试。',
    googleEmailMissing: 'Google 账户未返回可用邮箱。',
    googleEmailUnverified: 'Google 账户邮箱尚未验证，无法登录。',
    googleOauthFailed: 'Google 登录失败，请稍后再试。',
    accountDisabled: '这个账号已被禁用，请联系管理员。',
    authFailedSignin: '登录失败。',
    authFailedSignup: '注册失败。',
    authEmailExists: '这个邮箱已经注册，请直接登录。',
    authEmailNotVerified: '邮箱还没有验证。我们已重新发送验证邮件，请先打开邮箱完成验证。',
    authInvalidCredentials: '邮箱或密码错误，请重新输入。',
    authInvalidEmail: '请输入正确的邮箱地址。',
    authPasswordTooShort: '密码至少需要 10 位，并包含字母和数字。',
    authModeSignin: '登录',
    authModeSignup: '注册',
    authModeResetRequest: '发送重置链接',
    authModeResetConfirm: '设置新密码',
    authModeVerifyEmail: '验证邮箱',
    authTitleSignin: '登录 Metrovan AI',
    authTitleSignup: '注册 Metrovan AI',
    authTitleResetRequest: '重置密码',
    authTitleResetConfirm: '设置新密码',
    authTitleVerifyEmail: '正在验证邮箱',
    authSubtitleSignin: '进入你的修图工作台。',
    authSubtitleSignup: '创建账户后开始项目处理。',
    authSubtitleResetRequest: '输入注册邮箱，我们会发送一封密码重置邮件。',
    authSubtitleResetConfirm: '请输入新密码，完成后可以重新登录。',
    authSubtitleVerifyEmail: '我们正在确认你的邮箱验证链接。',
    authUseGoogle: '使用 Google 登录',
    authGoogleComingSoon: 'Google 登录将在正式配置后开启。',
    authUseEmail: '或使用邮箱继续',
    authName: '姓名',
    authEmail: '邮箱',
    authPassword: '密码',
    authPasswordPlaceholder: '请输入密码',
    authNewPassword: '新密码',
    authNewPasswordPlaceholder: '请输入新密码',
    authConfirmPassword: '确认密码',
    authConfirmPasswordPlaceholder: '请再次输入密码',
    authForgotPassword: '忘记密码？',
    authBackToLogin: '返回登录',
    authNoAccount: '没有账户？ 去注册',
    authHasAccount: '已有账户？ 去登录',
    authWorking: '处理中...',
    authMissingFields: '请输入邮箱和密码。',
    authMissingEmail: '请输入注册邮箱。',
    authResetTokenMissing: '重置链接缺少 token，请重新申请。',
    authVerifyTokenMissing: '验证链接缺少 token，请重新登录并重新发送验证邮件。',
    authPasswordMismatch: '两次密码输入不一致。',
    authRateLimited: '尝试次数过多，请稍后再试。',
    authVerificationEmailSent: '验证邮件已发送，请打开邮箱完成验证后再登录。',
    authEmailVerifiedSuccess: '邮箱验证成功，正在进入工作台。',
    authVerifyInvalidOrExpired: '验证链接无效或已过期，请重新登录并发送新的验证邮件。',
    authResetEmailSent: '如果这个邮箱已注册，重置链接会发送到你的邮箱。',
    authResetPasswordSuccess: '密码已重置，请使用新密码登录。',
    authResetInvalidOrExpired: '重置链接无效或已过期，请重新申请。',
    authFailedReset: '密码重置失败，请稍后再试。',
    signInSuccess: '登录成功，正在进入工作台。',
    signUpSuccess: '注册成功，正在进入工作台。',
    loadSessionFailed: '登录状态检查失败。',
    googleSuccess: 'Google 登录成功。',
    loadProjectsFailed: '加载项目失败。',
    loadBillingFailed: '加载账单失败。',
    noDownloadProject: '没有可下载的项目。',
    downloadDemo: '演示模式下不生成真实下载包。',
    downloadFailed: '下载生成失败。',
    downloadCustomRequired: '自定义尺寸至少填写长边或宽高。',
    downloadVariantRequired: '至少选择一种下载输出。',
    downloadSectionOrganize: '文件组织',
    downloadSectionSizes: '导出尺寸',
    downloadStageQueued: '排队中…',
    downloadStagePreflight: '检查文件…',
    downloadStagePackaging: '正在打包…',
    downloadStageUploading: '上传云端…',
    topUpDemo: '演示模式下不执行真实充值。',
    topUpSuccess: '积分充值成功。',
    topUpFailed: '积分充值失败。',
    topUpRedirecting: '正在跳转到 Stripe 安全支付...',
    stripePaymentSuccessTitle: 'Stripe 已确认付款',
    stripePaymentSuccessBody: '积分已到账。付款、收据和 Invoice 均由 Stripe 安全处理。',
    stripeReceiptLink: '查看 Stripe 收据',
    stripeInvoiceLink: '查看 Stripe Invoice',
    stripeInvoicePdfLink: '下载 Invoice PDF',
    stripeDocumentsPending: 'Stripe 正在生成收据/Invoice，稍后刷新账单即可查看。',
    redeemActivationSuccess: '激活码兑换成功，积分已到账。',
    redeemActivationFailed: '激活码兑换失败。',
    paymentCancelled: '支付已取消。',
    paymentConfirming: '正在确认支付结果...',
    createProjectNameRequired: '请先填写项目名。',
    createProjectFailed: '创建项目失败。',
    renamePrompt: '输入新的项目名',
    renameFailed: '重命名失败。',
    deleteProjectConfirm: (name: string) => `删除项目“${name}”？删除后会从工作台移除。`,
    deleteProjectFailed: '删除项目失败。',
    uploadFailed: '上传失败。',
    uploadUnsupportedFiles: (count: number) => `只支持 RAW 和 JPG/JPEG，已忽略 ${count} 个不支持文件。`,
    uploadDuplicateFiles: (count: number) => `已忽略 ${count} 张重复照片。`,
    uploadNoSupportedFiles: '只支持 RAW 和 JPG/JPEG，请重新选择照片。',
    createGroupFailed: '新建分组失败。',
    updateStepFailed: '更新步骤失败。',
    updateSceneFailed: '更新场景失败。',
    updateColorModeFailed: '更新颜色模式失败。',
    replacementColorInvalid: '请输入 6 位 HEX 色号，例如 #D2CBC1。',
    replacementColorFailed: '更新替换颜色失败。',
    moveGroupFailed: '移动分组失败。',
    deleteHdrConfirm: (name: string) => `删除照片组“${name}”？删除后会从当前项目移除。`,
    deleteHdrFailed: '删除照片组失败。',
    shiftExposureFailed: '切换曝光失败。',
    importPhotosFirst: '请先导入照片。',
    startProcessingFailed: '启动处理失败。',
    retryProcessing: '重新处理失败照片',
    reorderResultsFailed: '保存结果排序失败。',
    home: '首页',
    plansNav: '方案',
    examplesNav: '案例',
    workflowNav: '流程',
    faqNav: 'FAQ',
    landingSignIn: '登录',
    landingStartProject: '开始项目',
    landingViewExamples: '看处理效果',
    landingHeroBadge: '房产照片自动修图',
    landingHeroTitle: '整套房源修图',
    landingHeroAccent: '颜色一致，交付更快。',
    landingHeroSub: '上传原片，自动完成曝光、白墙、色偏和质感统一。适合摄影师、地产团队和高频交付工作室。',
    landingTrustFast: '浏览器上传',
    landingTrustColor: '真实前后对比',
    landingTrustBilling: '$0.25/张起',
    plansHeroKicker: '面向房产影像交付的增值方案',
    plansHeroTitle: '一张照片 · 一个积分 · 一次出片',
    plansHeroSub: '基础单价 0.25 美金 / 积分，充值越多、折扣越高，赠送积分自动到账，随充随用永不过期。',
    plansMetaUnit: ' / 积分',
    plansMetaPhoto: ' 1 积分 = 1 张',
    plansMetaMax: ' 最高折扣',
    plansTrustOutput: '高清输出',
    plansTrustFormats: 'RAW 格式',
    plansTrustSpeed: '单张处理',
    plansTrustCloud: '云端交付',
    plansLockBadge: '限时',
    plansLockTitle: '开发阶段 · 折扣终身锁定',
    plansLockSub: '现在购买的用户，所购档位折扣永久保留。例如 $2000 档 = 40% 折扣永久有效，日后价格调整也不受影响。',
    plansTagStarter: '入门体验',
    plansTagGrowth: '成长进阶',
    plansTagPro: '专业工作室',
    plansTagStudio: '团队旗舰',
    plansBestValue: '最超值',
    plansCredits: '到账积分',
    plansOffLabel: (n: number) => `立享 ${n}% 折扣`,
    plansBonusLabel: (n: number) => `赠送 ${n.toLocaleString()} 积分`,
    plansPerPhoto: '1 积分处理 1 张房产图',
    plansChoose: '选择此方案',
    plansBenefitsKicker: '方案权益',
    plansBenefitsTitle: '每一档都是完整的生产力',
    plansBen1Title: '业内领先的颜色还原',
    plansBen1Desc: '市面上还原房间本色最准的自动修图：墙色、曝光与整体观感跨房间对齐，整套房源保持同一视觉气质，不过曝、不偏色、不塑料感。',
    plansBen2Title: '失败自救 · 一键替换',
    plansBen2Desc: '万一修图结果不满意，不用联系客服、不用等人工重修 —— 直接在结果上点击色号重新生成，墙面颜色一键替换，交付节奏始终在你手里。',
    plansBen3Title: '材质与结构保护',
    plansBen3Desc: '智能识别木纹、石材、纺织面料，只修光色不伤纹理。',
    plansBen4Title: '极速交付',
    plansBen4Desc: '上传完成后不用久等，整套房源一次提交一次下完，不用隔夜渲染，也不用分批等。',
    plansBen5Title: '透明扣费',
    plansBen5Desc: '预估积分先显示，按成功张数扣点，失败不扣，账单随时可查。',
    plansBen6Title: '持续迭代 · 功能不断叠加',
    plansBen6Desc: '产品正处于快速开发阶段，新能力按版本滚动上线，已注册用户自动升级 —— 你买到的不是一套静态功能，而是一条持续成长的工具链。',
    plansScenesKicker: '合作模式',
    plansScenesTitle: '三种方式，按需选择',
    plansScene1Tag: '积分系统',
    plansScene1Title: '随心充值 · 按量付费',
    plansScene1Desc: '按上方档位灵活充值，1 积分 = 1 张图，无需本地硬件，打开浏览器即开即用。适合出图量波动大、想立刻上手的用户。',
    plansScene1MetaLabel: '起步',
    plansScene1MetaValue: '$100 起',
    plansScene2Tag: '买断软件',
    plansScene2Title: '一次付费 · 本地部署',
    plansScene2Desc: '软件买断版本，本地显卡 RTX 3090 起步即可运行。单张约 3 分钟，实际用时随输出尺寸浮动。适合长期稳定出片、数据不出本地的工作室。',
    plansScene2MetaLabel: '硬件要求',
    plansScene2MetaValue: 'GPU 3090+',
    plansScene3Tag: '企业深度合作',
    plansScene3Title: '$15,000 · 企业深度合作',
    plansScene3Desc: '面向需要长期自主管理和深度定制的团队，提供完整交付、使用培训和专属支持。适合希望把修图能力稳定接入自家业务线的公司。',
    plansScene3MetaLabel: '一次付费',
    plansScene3MetaValue: '$15,000',
    plansRecommend: '推荐档位',
    plansFaqKicker: '常见问题',
    plansFaqTitle: '关于充值、扣费与退款',
    plansFaq1Q: '积分会过期吗？',
    plansFaq1A: '不会。积分充值到账后长期有效，随充随用。',
    plansFaq2Q: '处理失败的图也会扣费吗？',
    plansFaq2A: '不会。预估积分仅用于显示，实际扣费按成功交付张数结算。',
    plansFaq3Q: '能开发票吗？',
    plansFaq3A: '可以。请在充值完成后通过账单页提交开票信息，支持个人和企业抬头。',
    plansFaq4Q: '可以退款吗？',
    plansFaq4A: '可以联系管理员人工处理。系统会先核对订单金额、到账积分、已消费积分和可退金额，再通过 Stripe 完成退款。',
    plansFaq5Q: '激活码怎么使用？',
    plansFaq5A: '在充值弹窗中填写激活码即可自动校验并叠加到本次充值，赠送积分同步到账。',
    plansCtaTitle: '准备好让整套房源保持一致气质了吗？',
    plansCtaSub: '注册账号即可体验，首次充值自动享受对应档位折扣。',
    plansCtaBtn: '立即开始',
    studioLabel: 'Metrovan AI 工作室',
    studioSubLabel: '房地产影像工作台',
    studioGuideOpen: '新手指引',
    studioGuideTitle: 'Studio 新手指引',
    studioGuideSubtitle: '按这个顺序完成一套照片。以后也可以从右上角重新打开。',
    studioGuideStepCount: (current: number, total: number) => `${current} / ${total}`,
    studioGuidePrev: '上一步',
    studioGuideNext: '下一步',
    studioGuideDone: '开始使用',
    studioGuideDontShow: '不再提醒',
    studioGuideStep1Title: '新建项目',
    studioGuideStep1Body: '先为这套房源创建一个项目，项目会保存照片分组、处理状态和下载结果。',
    studioGuideStep2Title: '导入照片',
    studioGuideStep2Body: '把 RAW 或 JPG 拖进上传区。浏览器会先读取缩略图和相机数据，不会立刻上传原片。',
    studioGuideStep3Title: '检查 HDR 分组',
    studioGuideStep3Body: '系统会按曝光自动分组。确认无误后继续上传处理，也可以继续添加照片。',
    studioGuideStep4Title: '确认发送',
    studioGuideStep4Body: '确认分组后再上传原图。上传完成并进入自动处理后，可以关闭浏览器。',
    studioGuideStep5Title: '查看结果',
    studioGuideStep5Body: '结果区可以拖拽排序、点开大图、调整裁剪曝光；可用吸管吸取其他墙面颜色或手动输入 HEX。每个项目前 10 次免费，之后每次 1 积分。',
    studioGuideStep6Title: '下载和积分',
    studioGuideStep6Body: '下载时选择 HD 原尺寸或自定义尺寸。处理按成功照片数扣积分，充值和账单在用户菜单里查看。',
    points: '积分',
    topUp: '充值',
    menuSettings: '设置',
    menuBilling: '账单',
    menuLogout: '退出',
    settingsTitle: '账户设置',
    settingsHint: '更新显示名称和界面语言。',
    settingsDisplayName: '显示名称',
    settingsEmail: '邮箱',
    settingsEmailHint: '邮箱当前不可修改。',
    settingsLanguage: '语言',
    settingsDisplayNameRequired: '请输入显示名称。',
    settingsSaved: '设置已保存。',
    settingsSaveFailed: '保存设置失败。',
    chinese: '中文',
    english: 'English',
    save: '保存',
    cancel: '取消',
    close: '关闭',
    historyProjects: '历史项目',
    historyProjectsHintDemo: '双击打开历史项目，使用打开、下载或删除管理记录。',
    historyProjectsHint: '双击打开历史项目，继续处理或查看结果。',
    newProject: '新建项目',
    rename: '重命名',
    open: '打开',
    download: '下载',
    delete: '删除',
    noProject: '还没有项目',
    noProjectHint: '先新建项目，再导入照片。',
    createFirstProject: '先创建一个项目',
    createFirstProjectHint: '创建项目后导入照片，开始检查照片分组。',
    currentProject: '当前项目',
    addressFallback: '未填写项目地址',
    processFlow: '处理流程',
    processFlowHint: '',
    waitingProcessing: '等待处理',
    waitingProcessingHint: '上传后会在这里显示处理状态。',
    processingProgress: '状态',
    estimatedPoints: '预计积分',
    uploadPhotos: '把照片拖到这里',
    uploadPhotosHint: '先在本地生成预览并自动分组，确认后再上传原图。',
    selectPhotos: '选择照片',
    addPhotos: '添加照片',
    uploadStarting: '正在读取并分组照片...',
    uploadProgress: (value: number) => `分组 ${value}%`,
    uploadPreparingProgress: (uploaded: number, total: number) =>
      uploaded > 0 ? `正在准备上传，已找到 ${uploaded}/${total} 张已上传文件` : `正在准备上传 ${total} 张，申请上传通道...`,
    uploadFileProgress: (uploaded: number, total: number) => `已上传 ${uploaded}/${total} 张`,
    uploadSpeedEtaProgress: (speed: string, eta: string) => `正在以 ${speed} 上传，还剩 ${eta}`,
    uploadVerifyingProgress: (uploaded: number, total: number) => `正在校验已上传 ${uploaded}/${total} 张，缺失文件将自动补传`,
    uploadRetryProgress: (name: string, attempt: number, maxAttempts: number, uploaded: number, total: number) =>
      `正在重试 ${name}（${attempt}/${maxAttempts}）· 已上传 ${uploaded}/${total} 张`,
    uploadFinalizeProgress: (total: number) => `${total} 张已上传，正在生成分组`,
    uploadOriginalsProgress: (value: number) => `上传 ${value}%`,
    uploadOriginalsTitle: '正在上传照片',
    uploadOriginalsDoNotClose: '正在上传照片，请勿退出浏览器。',
    uploadOriginalsReceived: '照片已上传到后端，正在启动自动处理。',
    uploadOriginalsCanClose: '照片已上传到服务器并开始自动处理，现在可以关闭浏览器。',
    processingGroupsTitle: '照片处理中',
    processingGroupsHint: '每组照片会自动显示处理状态，完成后直接显示结果图。',
    hdrItemReady: '等待上传',
    hdrItemProcessing: '处理中',
    hdrItemCompleted: '已完成',
    hdrItemFailed: '处理失败',
    demoVerticalFix: '垂直校正',
    demoCheckGrouping: '确认分组',
    demoAdjustGrouping: '调整分组',
    sendToProcess: '发送处理',
    reviewGrouping: '确认照片分组',
    reviewGroupingHint: '检查每组照片是否正确，确认后上传原图并自动处理。',
    createGroup: '新建分组',
    splitHdrGroup: '拆成单张',
    mergeHdrGroup: '合并到',
    mergeHdrPlaceholder: '合并到...',
    confirmSend: '确认发送',
    apply: '应用',
    groupNote: '建议发送前逐组确认目标颜色，避免整组观感不一致。',
    noPreview: '无预览图',
    localPreviewUnavailable: '无法本地预览',
    localImportPreviewMissingNotice: (count: number) => `${count} 张照片没有提取到本地预览，但已读取到相机数据，可继续分组。确认发送后会上传原图。`,
    localImportManualReviewNotice: (count: number) => `${count} 张照片没有读取到足够的相机数据，已按单张保留，请手动检查分组。`,
    localImportStatusNormal: '本地分组完成',
    localImportStatusNormalHint: '已读取相机数据和预览图。',
    localImportStatusPreviewMissing: '无法本地预览',
    localImportStatusPreviewMissingHint: '已读取相机数据，可继续分组。',
    localImportStatusManualReview: '需手动确认',
    localImportStatusManualReviewHint: '相机数据不足，已按单张保留。',
    results: '处理结果',
    resultsHint: '拖拽照片可调整下载后文件夹显示顺序，可按照外景、客厅、厨房、卧室排序。',
    clickToView: '点击查看大图',
    colorCardNo: '目标色卡',
    colorDropper: '吸取其他墙面颜色更改',
    colorDropperCompact: '吸取颜色',
    colorDropperUnsupported: '当前浏览器不支持吸管，请手动输入 HEX 颜色。',
    colorDropperFailed: '吸取颜色失败，请重试或手动输入。',
    regeneratePanelTitle: '重新生成',
    regeneratePanelHint: '吸取或填写其他墙面色卡。每个项目前 10 次免费，之后每次 1 积分。',
    resultCardColorHint: '其他墙面颜色',
    saveColorCard: '保存色卡',
    colorCardSaved: '色卡已保存，下次会自动显示。',
    colorCardAlreadySaved: '这个色卡已经在列表里。',
    deleteColorCard: '删除色卡',
    deleteColorCardConfirm: (color: string) => `删除色卡 ${color}？`,
    colorCardDeleted: '色卡已删除。',
    regenerateResult: '重新生成',
    regenerateResultCompact: '生成',
    regeneratingResult: '生成中',
    regeneratedResult: '继续生成',
    regenerateResultHint: '每个项目前 10 次免费，之后每次 1 积分。',
    regenerateResultStarted: '已开始重新生成，完成后这张图会自动更新。',
    regenerateResultFailed: '启动重新生成失败。',
    regenerateColorInvalid: '请输入正确的 HEX 颜色，例如 #F2E8D8。',
    noResults: '还没有结果',
    noResultsHint: '处理完成后，这里会显示所有结果图。',
    billingTitle: '积分与账单',
    billingHint: '处理前检查预计积分，完成后按实际成功张数扣点。',
    billingCurrentBalance: '当前余额',
    billingTopUpTotal: '累计充值',
    billingChargedTotal: '累计扣点',
    recentBilling: '最近账单',
    recentBillingHint: '包含充值记录与项目处理扣点。',
    billingOpenRecharge: '充值',
    noBilling: '还没有账单记录',
    noBillingHint: '充值后会在这里显示明细。',
    rechargeTitle: '积分充值',
    rechargeHint: '1 积分 = 1 张照片，基础单价 0.25 美金 / 积分。',
    rechargeCouponTitle: '激活码',
    rechargeCouponHint: '如有内测优惠或专属激活码，可以单独兑换积分，也可以充值时使用。',
    rechargeCouponLabel: '激活码',
    rechargeCouponPlaceholder: '输入激活码',
    rechargeCouponApplyHint: '直充积分码可直接兑换；折扣码会在充值付款时自动校验。',
    rechargeRedeemCode: '兑换积分',
    rechargePackageTitle: '充值档位',
    rechargeCustomTitle: '自定义金额',
    rechargeCustomLabel: '充值金额（USD）',
    rechargeCustomPlaceholder: '输入金额',
    rechargeCustomHint: '自定义金额无固定档位折扣，按 $0.25 / 积分向下取整；激活码仍可叠加。',
    rechargeCustomInvalid: '请输入 $1 到 $50,000 之间的有效金额。',
    rechargeCustomSummary: '自定义充值',
    rechargePayNow: '立即充值',
    rechargeYouPay: '实付',
    rechargeReceive: '到账积分',
    rechargeSave: '优惠',
    rechargeBonus: '额外赠送',
    createProjectTitle: '新建项目',
    projectName: '项目名称',
    projectAddress: '地址 / 备注',
    createProject: '创建项目',
    downloadSettings: '下载设置',
    downloadFolderMode: '文件夹结构',
    downloadFolderGrouped: '分文件夹（HD / Custom）',
    downloadFolderFlat: '单文件夹平铺',
    downloadNamingMode: '命名规则',
    downloadNamingSequence: '项目名 + 顺序',
    downloadNamingOriginal: '原文件名',
    downloadNamingCustomPrefix: '自定义前缀 + 顺序',
    downloadCustomPrefix: '自定义前缀',
    downloadHdTitle: 'HD 原尺寸',
    downloadHdHint: '保留当前结果图尺寸和排序。',
    downloadCustomTitle: '自定义尺寸',
    downloadCustomHint: '可填长边，或直接填宽高。',
    downloadFolderLabel: '文件夹标签',
    downloadLongEdge: '长边',
    downloadWidth: '宽度',
    downloadHeight: '高度',
    downloadNote: '下载包会沿用当前结果排序。平铺模式下会自动附加变体后缀，避免同名覆盖。',
    downloadGenerating: '正在生成...',
    downloadGenerate: '生成下载包'
  },
  en: {
    stepLabels: ['Import', 'Review', 'Upload', 'Done'] as const,
    demoStepLabels: ['Import', 'Review', 'Upload', 'Start'] as const,
    stepHints: ['Import photos and create local previews.', 'Confirm the automatic grouping.', 'Upload photos and start processing.', 'Review and sort the finished results online.'] as const,
    scene: { interior: 'Interior', exterior: 'Exterior', pending: 'Pending' } as const,
    colorMode: { default: 'Default Color', replace: 'Replace Color' } as const,
    status: {
      completed: 'Completed',
      processing: 'Processing',
      uploading: 'Uploading',
      review: 'Reviewing groups',
      importing: 'Loading Images',
      failed: 'Failed'
    } as const,
    connectionFailed: 'Unable to reach the service. Refresh and try again.',
    googleConfiguredMissing: 'Google sign-in is not configured yet.',
    googleOauthStateFailed: 'Google sign-in verification failed. Please try again.',
    googleEmailMissing: 'No usable email was returned by Google.',
    googleEmailUnverified: 'The Google account email is not verified.',
    googleOauthFailed: 'Google sign-in failed. Please try again later.',
    accountDisabled: 'This account has been disabled. Please contact an administrator.',
    authFailedSignin: 'Sign-in failed.',
    authFailedSignup: 'Sign-up failed.',
    authEmailExists: 'This email is already registered. Please sign in instead.',
    authEmailNotVerified: 'This email is not verified yet. We sent a new verification email. Check your inbox first.',
    authInvalidCredentials: 'Incorrect email or password. Please try again.',
    authInvalidEmail: 'Enter a valid email address.',
    authPasswordTooShort: 'Password must be at least 10 characters and include letters and numbers.',
    authModeSignin: 'Sign In',
    authModeSignup: 'Sign Up',
    authModeResetRequest: 'Send Reset Link',
    authModeResetConfirm: 'Set New Password',
    authModeVerifyEmail: 'Verify Email',
    authTitleSignin: 'Sign in to Metrovan AI',
    authTitleSignup: 'Create your Metrovan AI account',
    authTitleResetRequest: 'Reset your password',
    authTitleResetConfirm: 'Set a new password',
    authTitleVerifyEmail: 'Verifying your email',
    authSubtitleSignin: 'Enter your editing workspace.',
    authSubtitleSignup: 'Create an account and start processing projects.',
    authSubtitleResetRequest: 'Enter your account email and we will send a password reset link.',
    authSubtitleResetConfirm: 'Enter a new password, then sign in again.',
    authSubtitleVerifyEmail: 'We are confirming your email verification link.',
    authUseGoogle: 'Continue with Google',
    authGoogleComingSoon: 'Google sign-in will be enabled after final configuration.',
    authUseEmail: 'Or continue with email',
    authName: 'Name',
    authEmail: 'Email',
    authPassword: 'Password',
    authPasswordPlaceholder: 'Enter your password',
    authNewPassword: 'New password',
    authNewPasswordPlaceholder: 'Enter a new password',
    authConfirmPassword: 'Confirm password',
    authConfirmPasswordPlaceholder: 'Enter your password again',
    authForgotPassword: 'Forgot password?',
    authBackToLogin: 'Back to sign in',
    authNoAccount: "Don't have an account? Sign up",
    authHasAccount: 'Already have an account? Sign in',
    authWorking: 'Working...',
    authMissingFields: 'Enter your email and password.',
    authMissingEmail: 'Enter your account email.',
    authResetTokenMissing: 'This reset link is missing a token. Request a new link.',
    authVerifyTokenMissing: 'This verification link is missing a token. Sign in again to send a new verification email.',
    authPasswordMismatch: 'Passwords do not match.',
    authRateLimited: 'Too many attempts. Please try again later.',
    authVerificationEmailSent: 'Verification email sent. Check your inbox before signing in.',
    authEmailVerifiedSuccess: 'Email verified. Redirecting to your workspace.',
    authVerifyInvalidOrExpired: 'This verification link is invalid or expired. Sign in again to send a new email.',
    authResetEmailSent: 'If this email is registered, a reset link has been sent.',
    authResetPasswordSuccess: 'Your password has been reset. Please sign in with the new password.',
    authResetInvalidOrExpired: 'This reset link is invalid or expired. Request a new link.',
    authFailedReset: 'Password reset failed. Please try again later.',
    signInSuccess: 'Signed in. Redirecting to your workspace.',
    signUpSuccess: 'Account created. Redirecting to your workspace.',
    loadSessionFailed: 'Failed to check your sign-in session.',
    googleSuccess: 'Google sign-in succeeded.',
    loadProjectsFailed: 'Failed to load projects.',
    loadBillingFailed: 'Failed to load billing.',
    noDownloadProject: 'No downloadable project is available.',
    downloadDemo: 'Demo mode does not generate real download packages.',
    downloadFailed: 'Failed to generate the download package.',
    downloadCustomRequired: 'Enter either a long edge or a width and height for the custom size.',
    downloadVariantRequired: 'Select at least one output variant.',
    downloadSectionOrganize: 'File organization',
    downloadSectionSizes: 'Export sizes',
    downloadStageQueued: 'Queued…',
    downloadStagePreflight: 'Checking files…',
    downloadStagePackaging: 'Packaging…',
    downloadStageUploading: 'Uploading…',
    topUpDemo: 'Demo mode does not perform real top-ups.',
    topUpSuccess: 'Credits added successfully.',
    topUpFailed: 'Top-up failed.',
    topUpRedirecting: 'Redirecting to secure Stripe checkout...',
    stripePaymentSuccessTitle: 'Stripe payment confirmed',
    stripePaymentSuccessBody: 'Credits are available. Payment, receipt, and invoice are handled securely by Stripe.',
    stripeReceiptLink: 'View Stripe receipt',
    stripeInvoiceLink: 'View Stripe invoice',
    stripeInvoicePdfLink: 'Download invoice PDF',
    stripeDocumentsPending: 'Stripe is generating the receipt/invoice. Refresh billing shortly to view it.',
    redeemActivationSuccess: 'Activation code redeemed. Credits are now available.',
    redeemActivationFailed: 'Activation code redemption failed.',
    paymentCancelled: 'Payment was cancelled.',
    paymentConfirming: 'Confirming payment...',
    createProjectNameRequired: 'Enter a project name first.',
    createProjectFailed: 'Failed to create the project.',
    renamePrompt: 'Enter a new project name',
    renameFailed: 'Failed to rename the project.',
    deleteProjectConfirm: (name: string) => `Delete "${name}" from your workspace?`,
    deleteProjectFailed: 'Failed to delete the project.',
    uploadFailed: 'Upload failed.',
    uploadUnsupportedFiles: (count: number) => `Only RAW and JPG/JPEG files are supported. ${count} unsupported file${count === 1 ? '' : 's'} ignored.`,
    uploadDuplicateFiles: (count: number) => `${count} duplicate ${count === 1 ? 'photo was' : 'photos were'} ignored.`,
    uploadNoSupportedFiles: 'Only RAW and JPG/JPEG files are supported. Please choose photos again.',
    createGroupFailed: 'Failed to create a group.',
    updateStepFailed: 'Failed to update the step.',
    updateSceneFailed: 'Failed to update the scene type.',
    updateColorModeFailed: 'Failed to update the color mode.',
    replacementColorInvalid: 'Enter a valid 6-digit HEX value, such as #D2CBC1.',
    replacementColorFailed: 'Failed to update the replacement color.',
    moveGroupFailed: 'Failed to move the photo group.',
    deleteHdrConfirm: (name: string) => `Delete photo group "${name}" from this project?`,
    deleteHdrFailed: 'Failed to delete the photo group.',
    shiftExposureFailed: 'Failed to switch the exposure.',
    importPhotosFirst: 'Import photos first.',
    startProcessingFailed: 'Failed to start processing.',
    retryProcessing: 'Retry failed photos',
    reorderResultsFailed: 'Failed to save the result order.',
    home: 'Home',
    plansNav: 'Plans',
    examplesNav: 'Examples',
    workflowNav: 'Workflow',
    faqNav: 'FAQ',
    landingSignIn: 'Sign In',
    landingStartProject: 'Start a Project',
    landingViewExamples: 'View Examples',
    landingHeroBadge: 'Real-estate photo retouching',
    landingHeroTitle: 'Listing photos cleaned up',
    landingHeroAccent: 'consistent color, faster delivery.',
    landingHeroSub: 'Upload originals and automatically align exposure, wall color, color cast, and material realism across the full property set.',
    landingTrustFast: 'Browser upload',
    landingTrustColor: 'Real before/after',
    landingTrustBilling: 'From $0.25/photo',
    plansHeroKicker: 'Value plans for real-estate image delivery',
    plansHeroTitle: 'One photo · one credit · one clean delivery',
    plansHeroSub: 'Base rate $0.25 USD per credit. Larger top-ups unlock bigger discounts and bonus credits. Credits never expire.',
    plansMetaUnit: ' / credit',
    plansMetaPhoto: ' 1 credit = 1 photo',
    plansMetaMax: ' max discount',
    plansTrustOutput: 'HD Output',
    plansTrustFormats: 'RAW Formats',
    plansTrustSpeed: 'Per Photo',
    plansTrustCloud: 'Cloud Delivered',
    plansLockBadge: 'Limited',
    plansLockTitle: 'Early-access pricing · locked in for life',
    plansLockSub: 'Buy during the early-access phase and your tier discount stays yours forever. The $2000 plan keeps its 40% off on every future top-up — even after prices return to standard.',
    plansTagStarter: 'Starter',
    plansTagGrowth: 'Growth',
    plansTagPro: 'Pro Studio',
    plansTagStudio: 'Flagship Team',
    plansBestValue: 'Best value',
    plansCredits: 'credits delivered',
    plansOffLabel: (n: number) => `${n}% off instantly`,
    plansBonusLabel: (n: number) => `+${n.toLocaleString()} bonus credits`,
    plansPerPhoto: '1 credit processes 1 listing photo',
    plansChoose: 'Choose this plan',
    plansBenefitsKicker: 'Plan benefits',
    plansBenefitsTitle: 'Every tier is a complete production line',
    plansBen1Title: 'Best-in-class color fidelity',
    plansBen1Desc: 'The most faithful automatic retouch for listing interiors on the market. Wall color, exposure and overall tone align across rooms — no overexposure, no color cast, no plastic look.',
    plansBen2Title: 'Self-service recovery',
    plansBen2Desc: 'If a render does not land the first time, you do not wait for a human retoucher or a support ticket. Click a color swatch, regenerate, and the wall color swaps instantly — your delivery timeline stays yours.',
    plansBen3Title: 'Material & structure safe',
    plansBen3Desc: 'Detects wood, stone and textiles — corrects light and color without harming texture.',
    plansBen4Title: 'Fast turnaround',
    plansBen4Desc: 'Upload once and pull down the whole listing in one sitting — no overnight renders, no piece-by-piece waiting.',
    plansBen5Title: 'Transparent billing',
    plansBen5Desc: 'See an estimate up front. Only successful frames are charged. Full history is always in the billing page.',
    plansBen6Title: 'Always evolving',
    plansBen6Desc: 'We are in active development — new capabilities ship continuously and existing users upgrade automatically. You are not buying a frozen product, you are buying a tool that keeps getting better.',
    plansScenesKicker: 'How to work with us',
    plansScenesTitle: 'Three options — pick what fits',
    plansScene1Tag: 'Credit system',
    plansScene1Title: 'Pay as you go · top up anytime',
    plansScene1Desc: 'Top up flexibly using the tiers above. 1 credit = 1 photo. No local hardware — open a browser and start. Ideal for variable volume or teams that want to get moving right away.',
    plansScene1MetaLabel: 'Start from',
    plansScene1MetaValue: '$100',
    plansScene2Tag: 'Software license',
    plansScene2Title: 'One-time payment · local deployment',
    plansScene2Desc: 'Perpetual software license. Runs locally on an RTX 3090 or better. Around 3 minutes per photo, varying with output resolution. Best for studios with steady volume and strict data-locality requirements.',
    plansScene2MetaLabel: 'Hardware',
    plansScene2MetaValue: 'GPU 3090+',
    plansScene3Tag: 'Enterprise partnership',
    plansScene3Title: '$15,000 · enterprise partnership',
    plansScene3Desc: 'For teams that need long-term control and deeper customization, we provide full delivery, onboarding, and dedicated support so the service can fit into your existing business line.',
    plansScene3MetaLabel: 'One-time',
    plansScene3MetaValue: '$15,000',
    plansRecommend: 'Recommended',
    plansFaqKicker: 'FAQ',
    plansFaqTitle: 'Top-ups, usage, refunds',
    plansFaq1Q: 'Do credits expire?',
    plansFaq1A: 'No. Once credits land in your account they stay valid indefinitely.',
    plansFaq2Q: 'Am I charged for failed renders?',
    plansFaq2A: 'No. The estimated credits are for preview only. You are only billed for successfully delivered frames.',
    plansFaq3Q: 'Can I get an invoice?',
    plansFaq3A: 'Yes. Submit invoice details from the billing page after topping up — both personal and company titles are supported.',
    plansFaq4Q: 'Can I request a refund?',
    plansFaq4A: 'Yes. Refunds are handled manually by an admin after checking the order amount, delivered credits, consumed credits, refundable amount, and remaining balance.',
    plansFaq5Q: 'How do activation codes work?',
    plansFaq5A: 'Enter the code in the top-up modal. It is validated and applied automatically, and any bonus credits land with the top-up.',
    plansCtaTitle: 'Ready to keep every listing on one visual wavelength?',
    plansCtaSub: 'Create an account to try it. Your first top-up instantly earns the matching tier discount.',
    plansCtaBtn: 'Start now',
    studioLabel: 'Metrovan AI Studio',
    studioSubLabel: 'Real estate media workspace',
    studioGuideOpen: 'Guide',
    studioGuideTitle: 'Studio guide',
    studioGuideSubtitle: 'Follow this order to finish one listing. You can reopen this from the top right.',
    studioGuideStepCount: (current: number, total: number) => `${current} / ${total}`,
    studioGuidePrev: 'Back',
    studioGuideNext: 'Next',
    studioGuideDone: 'Start',
    studioGuideDontShow: 'Do not show again',
    studioGuideStep1Title: 'Create a project',
    studioGuideStep1Body: 'Create one project per listing. It stores grouping, processing status, and final downloads.',
    studioGuideStep2Title: 'Import photos',
    studioGuideStep2Body: 'Drop RAW or JPG files into the upload area. The browser reads previews and camera data before originals upload.',
    studioGuideStep3Title: 'Review HDR groups',
    studioGuideStep3Body: 'Photos are grouped by exposure. If needed, split singles, merge groups, or add more photos before sending.',
    studioGuideStep4Title: 'Confirm and send',
    studioGuideStep4Body: 'After confirming groups, originals upload. Once upload is complete and processing starts, you can close the browser.',
    studioGuideStep5Title: 'Review results',
    studioGuideStep5Body: 'Drag to reorder, open a large preview, adjust crop or exposure, then pick another wall color or enter HEX. Each project includes 10 free regenerations; later runs cost 1 credit each.',
    studioGuideStep6Title: 'Download and credits',
    studioGuideStep6Body: 'Download HD original size or custom size. Credits are charged only for successful images; billing is in the user menu.',
    points: 'Credits',
    topUp: 'Top up',
    menuSettings: 'Settings',
    menuBilling: 'Billing',
    menuLogout: 'Log out',
    settingsTitle: 'Account settings',
    settingsHint: 'Update your display name and interface language.',
    settingsDisplayName: 'Display name',
    settingsEmail: 'Email',
    settingsEmailHint: 'Email cannot be changed here.',
    settingsLanguage: 'Language',
    settingsDisplayNameRequired: 'Enter a display name.',
    settingsSaved: 'Settings saved.',
    settingsSaveFailed: 'Failed to save settings.',
    chinese: 'Chinese',
    english: 'English',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    historyProjects: 'Project history',
    historyProjectsHintDemo: 'Double-click a project to open it and manage open, download, or delete actions.',
    historyProjectsHint: 'Double-click a project to reopen it and continue processing or review results.',
    newProject: 'New Project',
    rename: 'Rename',
    open: 'Open',
    download: 'Download',
    delete: 'Delete',
    noProject: 'No projects yet',
    noProjectHint: 'Create a project first, then import photos.',
    createFirstProject: 'Create your first project',
    createFirstProjectHint: 'Start a project, import photos, and review grouping.',
    currentProject: 'Current Project',
    addressFallback: 'No project address added',
    processFlow: 'Process',
    processFlowHint: '',
    waitingProcessing: 'Waiting to process',
    waitingProcessingHint: 'Processing status will appear here after upload.',
    processingProgress: 'Status',
    estimatedPoints: 'Estimated credits',
    uploadPhotos: 'Drop photos here',
    uploadPhotosHint: 'Create local previews and automatic groups first, then upload the originals after confirmation.',
    selectPhotos: 'Select Photos',
    addPhotos: 'Add Photos',
    uploadStarting: 'Reading and grouping photos...',
    uploadProgress: (value: number) => `Grouping ${value}%`,
    uploadPreparingProgress: (uploaded: number, total: number) =>
      uploaded > 0 ? `Preparing upload; found ${uploaded}/${total} already uploaded` : `Preparing ${total} files and requesting upload slots...`,
    uploadFileProgress: (uploaded: number, total: number) => `Uploaded ${uploaded}/${total}`,
    uploadSpeedEtaProgress: (speed: string, eta: string) => `Uploading at ${speed}, ${eta} remaining`,
    uploadVerifyingProgress: (uploaded: number, total: number) => `Verifying uploaded files ${uploaded}/${total}; missing files will resume`,
    uploadRetryProgress: (name: string, attempt: number, maxAttempts: number, uploaded: number, total: number) =>
      `Retrying ${name} (${attempt}/${maxAttempts}) · Uploaded ${uploaded}/${total}`,
    uploadFinalizeProgress: (total: number) => `${total} uploaded. Building groups`,
    uploadOriginalsProgress: (value: number) => `Uploading ${value}%`,
    uploadOriginalsTitle: 'Uploading photos',
    uploadOriginalsDoNotClose: 'Uploading photos. Please do not close the browser.',
    uploadOriginalsReceived: 'Photos are uploaded to the backend. Starting automatic processing.',
    uploadOriginalsCanClose: 'Photos are uploaded and processing has started. You can close the browser now.',
    processingGroupsTitle: 'Processing photos',
    processingGroupsHint: 'Each group shows live status. Finished groups switch to the processed photo automatically.',
    hdrItemReady: 'Waiting to upload',
    hdrItemProcessing: 'Processing',
    hdrItemCompleted: 'Completed',
    hdrItemFailed: 'Failed',
    demoVerticalFix: 'Vertical Fix',
    demoCheckGrouping: 'Check Groups',
    demoAdjustGrouping: 'Adjust Groups',
    sendToProcess: 'Send to Process',
    reviewGrouping: 'Review groups',
    reviewGroupingHint: 'Check each photo group, then upload originals and start processing automatically.',
    createGroup: 'New Group',
    splitHdrGroup: 'Split Singles',
    mergeHdrGroup: 'Merge to',
    mergeHdrPlaceholder: 'Merge to...',
    confirmSend: 'Confirm & Send',
    apply: 'Apply',
    groupNote: 'Confirm each target color before sending to avoid inconsistent color across the group.',
    noPreview: 'No preview',
    localPreviewUnavailable: 'Local preview unavailable',
    localImportPreviewMissingNotice: (count: number) => `${count} ${count === 1 ? 'photo has' : 'photos have'} no local preview, but camera metadata was read and grouping can continue. Originals upload after confirmation.`,
    localImportManualReviewNotice: (count: number) => `${count} ${count === 1 ? 'photo has' : 'photos have'} insufficient camera metadata and was kept as a single item. Check grouping manually.`,
    localImportStatusNormal: 'Local grouping ready',
    localImportStatusNormalHint: 'Camera metadata and preview are available.',
    localImportStatusPreviewMissing: 'No local preview',
    localImportStatusPreviewMissingHint: 'Camera metadata is available for grouping.',
    localImportStatusManualReview: 'Manual check needed',
    localImportStatusManualReviewHint: 'Metadata is insufficient, so this stays single.',
    results: 'Results',
    resultsHint: 'Drag photos to control the folder order in the final download.',
    clickToView: 'Click to view large image',
    colorCardNo: 'Target color',
    colorDropper: 'Pick another wall color',
    colorDropperCompact: 'Pick color',
    colorDropperUnsupported: 'This browser does not support the eyedropper. Enter a HEX color manually.',
    colorDropperFailed: 'Color picking failed. Try again or enter HEX manually.',
    regeneratePanelTitle: 'Regenerate',
    regeneratePanelHint: 'Pick or enter another wall color. Each project includes 10 free regenerations; later runs cost 1 credit each.',
    resultCardColorHint: 'Another wall color',
    saveColorCard: 'Save card',
    colorCardSaved: 'Color card saved and will appear next time.',
    colorCardAlreadySaved: 'This color card is already in the list.',
    deleteColorCard: 'Delete card',
    deleteColorCardConfirm: (color: string) => `Delete color card ${color}?`,
    colorCardDeleted: 'Color card deleted.',
    regenerateResult: 'Regenerate',
    regenerateResultCompact: 'Run',
    regeneratingResult: 'Generating',
    regeneratedResult: 'Regenerate again',
    regenerateResultHint: 'Each project includes 10 free regenerations; later runs cost 1 credit each.',
    regenerateResultStarted: 'Regeneration started. This image will update when it finishes.',
    regenerateResultFailed: 'Failed to start regeneration.',
    regenerateColorInvalid: 'Enter a valid HEX color, for example #F2E8D8.',
    noResults: 'No results yet',
    noResultsHint: 'Finished images will appear here after processing.',
    billingTitle: 'Credits & billing',
    billingHint: 'Estimated credits are checked before processing. Final credits are charged by successful images.',
    billingCurrentBalance: 'Current balance',
    billingTopUpTotal: 'Total top-up',
    billingChargedTotal: 'Total charged',
    recentBilling: 'Recent billing',
    recentBillingHint: 'Includes both top-ups and per-project processing charges.',
    billingOpenRecharge: 'Recharge',
    noBilling: 'No billing history yet',
    noBillingHint: 'Billing details will appear here after your first top-up.',
    rechargeTitle: 'Recharge credits',
    rechargeHint: '1 credit = 1 photo. Base rate: $0.25 USD per credit.',
    rechargeCouponTitle: 'Activation code',
    rechargeCouponHint: 'Enter a beta or private activation code to redeem credits or apply it during recharge.',
    rechargeCouponLabel: 'Activation code',
    rechargeCouponPlaceholder: 'Enter code',
    rechargeCouponApplyHint: 'Credit codes can be redeemed directly. Discount codes are validated during checkout.',
    rechargeRedeemCode: 'Redeem credits',
    rechargePackageTitle: 'Recharge tiers',
    rechargeCustomTitle: 'Custom amount',
    rechargeCustomLabel: 'Amount (USD)',
    rechargeCustomPlaceholder: 'Enter amount',
    rechargeCustomHint: 'Custom amounts have no tier discount by default. Credits are rounded down at $0.25 each; activation codes still apply.',
    rechargeCustomInvalid: 'Enter a valid amount between $1 and $50,000.',
    rechargeCustomSummary: 'Custom recharge',
    rechargePayNow: 'Recharge now',
    rechargeYouPay: 'Pay now',
    rechargeReceive: 'Credits received',
    rechargeSave: 'Discount',
    rechargeBonus: 'Bonus credits',
    createProjectTitle: 'Create project',
    projectName: 'Project name',
    projectAddress: 'Address / Notes',
    createProject: 'Create Project',
    downloadSettings: 'Download settings',
    downloadFolderMode: 'Folder structure',
    downloadFolderGrouped: 'Grouped folders (HD / Custom)',
    downloadFolderFlat: 'Flat single folder',
    downloadNamingMode: 'Naming',
    downloadNamingSequence: 'Project name + sequence',
    downloadNamingOriginal: 'Original filename',
    downloadNamingCustomPrefix: 'Custom prefix + sequence',
    downloadCustomPrefix: 'Custom prefix',
    downloadHdTitle: 'HD original size',
    downloadHdHint: 'Keep the current result size and order.',
    downloadCustomTitle: 'Custom size',
    downloadCustomHint: 'Enter a long edge, or specify width and height.',
    downloadFolderLabel: 'Folder label',
    downloadLongEdge: 'Long edge',
    downloadWidth: 'Width',
    downloadHeight: 'Height',
    downloadNote: 'The package follows the current result order. Flat mode appends variant suffixes to avoid filename collisions.',
    downloadGenerating: 'Generating...',
    downloadGenerate: 'Generate ZIP'
  }
} satisfies Record<UiLocale, Record<string, unknown>>;
