import type { LandingPageCopy } from './pages/LandingPage';

export type UiLocale = 'zh' | 'en';

export const LANDING_COPY = {
  zh: {
    home: '首页',
    plansNav: '方案',
    examplesNav: '案例',
    workflowNav: '流程',
    faqNav: 'FAQ',
    landingSignIn: '登录',
    landingStartProject: '开始项目',
    landingViewExamples: '看处理效果',
    landingHeroBadge: '房产照片自动修图',
    landingHeroTitle: '整套房源修图',
    landingHeroAccent: '颜色一致，交付更快。',
    landingHeroSub: '上传原片，自动完成曝光、白墙、色偏和质感统一。适合摄影师、地产团队和高频交付工作室。',
    landingTrustFast: '浏览器上传',
    landingTrustColor: '真实前后对比',
    landingTrustBilling: '$0.25/张起',
    plansHeroKicker: '面向房产影像交付的增值方案',
    plansHeroTitle: '一张照片 · 一个积分 · 一次出片',
    plansHeroSub: '基础单价 0.25 美金 / 积分，充值越多、折扣越高，赠送积分自动到账，随充随用永不过期。',
    plansMetaUnit: ' / 积分',
    plansMetaPhoto: ' 1 积分 = 1 张',
    plansMetaMax: ' 最高折扣',
    plansLockBadge: '限时',
    plansLockTitle: '开发阶段 · 折扣终身锁定',
    plansLockSub: '现在购买的用户，所购档位折扣永久保留。例如 $2000 档 = 40% 折扣永久有效，日后价格调整也不受影响。',
    plansTagStarter: '入门体验',
    plansTagGrowth: '成长进阶',
    plansTagPro: '专业工作室',
    plansTagStudio: '团队旗舰',
    plansBestValue: '最超值',
    plansCredits: '到账积分',
    plansOffLabel: (n: number) => `立享 ${n}% 折扣`,
    plansBonusLabel: (n: number) => `赠送 ${n.toLocaleString()} 积分`,
    plansPerPhoto: '1 积分处理 1 张房产图',
    plansChoose: '选择此方案',
    plansBenefitsKicker: '方案权益',
    plansBenefitsTitle: '每一档都是完整的生产力',
    plansBen1Title: '业内领先的颜色还原',
    plansBen1Desc: '市面上还原房间本色最准的自动修图：墙色、曝光与整体观感跨房间对齐，整套房源保持同一视觉气质，不过曝、不偏色、不塑料感。',
    plansBen2Title: '失败自救 · 一键替换',
    plansBen2Desc: '万一修图结果不满意，不用联系客服、不用等人工重修 —— 直接在结果上点击色号重新生成，墙面颜色一键替换，交付节奏始终在你手里。',
    plansBen3Title: '材质与结构保护',
    plansBen3Desc: '智能识别木纹、石材、纺织面料，只修光色不伤纹理。',
    plansBen4Title: '极速交付',
    plansBen4Desc: '上传完成后不用久等，整套房源一次提交一次下完，不用隔夜渲染，也不用分批等。',
    plansBen5Title: '透明扣费',
    plansBen5Desc: '预估积分先显示，按成功张数扣点，失败不扣，账单随时可查。',
    plansBen6Title: '持续迭代 · 功能不断叠加',
    plansBen6Desc: '产品正处于快速开发阶段，新能力按版本滚动上线，已注册用户自动升级 —— 你买到的不是一套静态功能，而是一条持续成长的工具链。',
    plansScenesKicker: '合作模式',
    plansScenesTitle: '三种方式，按需选择',
    plansScene1Tag: '积分系统',
    plansScene1Title: '随心充值 · 按量付费',
    plansScene1Desc: '按上方档位灵活充值，1 积分 = 1 张图，无需本地硬件，打开浏览器即开即用。适合出图量波动大、想立刻上手的用户。',
    plansScene1MetaLabel: '起步',
    plansScene1MetaValue: '$100 起',
    plansScene2Tag: '买断软件',
    plansScene2Title: '一次付费 · 本地部署',
    plansScene2Desc: '软件买断版本，本地显卡 RTX 3090 起步即可运行。单张约 3 分钟，实际用时随输出尺寸浮动。适合长期稳定出片、数据不出本地的工作室。',
    plansScene2MetaLabel: '硬件要求',
    plansScene2MetaValue: 'GPU 3090+',
    plansScene3Tag: '企业深度合作',
    plansScene3Title: '$15,000 · 企业深度合作',
    plansScene3Desc: '面向需要长期自主管理和深度定制的团队，提供完整交付、使用培训和专属支持。适合希望把修图能力稳定接入自家业务线的公司。',
    plansScene3MetaLabel: '一次付费',
    plansScene3MetaValue: '$15,000',
    plansFaqKicker: '常见问题',
    plansFaqTitle: '关于充值、扣费与退款',
    plansFaq1Q: '积分会过期吗？',
    plansFaq1A: '不会。积分充值到账后长期有效，随充随用。',
    plansFaq2Q: '处理失败的图也会扣费吗？',
    plansFaq2A: '不会。预估积分仅用于显示，实际扣费按成功交付张数结算。',
    plansFaq3Q: '能开发票吗？',
    plansFaq3A: '可以。请在充值完成后通过账单页提交开票信息，支持个人和企业抬头。',
    plansFaq4Q: '可以退款吗？',
    plansFaq4A: '可以联系管理员人工处理。系统会先核对订单金额、到账积分、已消费积分和可退金额，再通过 Stripe 完成退款。',
    plansFaq5Q: '激活码怎么使用？',
    plansFaq5A: '在充值弹窗中填写激活码即可自动校验并叠加到本次充值，赠送积分同步到账。',
    plansCtaTitle: '准备好让整套房源保持一致气质了吗？',
    plansCtaSub: '注册账号即可体验，首次充值自动享受对应档位折扣。',
    plansCtaBtn: '立即开始',
    studioLabel: 'Metrovan AI 工作室'
  },
  en: {
    home: 'Home',
    plansNav: 'Plans',
    examplesNav: 'Examples',
    workflowNav: 'Workflow',
    faqNav: 'FAQ',
    landingSignIn: 'Sign In',
    landingStartProject: 'Start a Project',
    landingViewExamples: 'View Examples',
    landingHeroBadge: 'Real-estate photo retouching',
    landingHeroTitle: 'Listing photos cleaned up',
    landingHeroAccent: 'consistent color, faster delivery.',
    landingHeroSub: 'Upload originals and automatically align exposure, wall color, color cast, and material realism across the full property set.',
    landingTrustFast: 'Browser upload',
    landingTrustColor: 'Real before/after',
    landingTrustBilling: 'From $0.25/photo',
    plansHeroKicker: 'Value plans for real-estate image delivery',
    plansHeroTitle: 'One photo · one credit · one clean delivery',
    plansHeroSub: 'Base rate $0.25 USD per credit. Larger top-ups unlock bigger discounts and bonus credits. Credits never expire.',
    plansMetaUnit: ' / credit',
    plansMetaPhoto: ' 1 credit = 1 photo',
    plansMetaMax: ' max discount',
    plansLockBadge: 'Limited',
    plansLockTitle: 'Early-access pricing · locked in for life',
    plansLockSub: 'Buy during the early-access phase and your tier discount stays yours forever. The $2000 plan keeps its 40% off on every future top-up — even after prices return to standard.',
    plansTagStarter: 'Starter',
    plansTagGrowth: 'Growth',
    plansTagPro: 'Pro Studio',
    plansTagStudio: 'Flagship Team',
    plansBestValue: 'Best value',
    plansCredits: 'credits delivered',
    plansOffLabel: (n: number) => `${n}% off instantly`,
    plansBonusLabel: (n: number) => `+${n.toLocaleString()} bonus credits`,
    plansPerPhoto: '1 credit processes 1 listing photo',
    plansChoose: 'Choose this plan',
    plansBenefitsKicker: 'Plan benefits',
    plansBenefitsTitle: 'Every tier is a complete production line',
    plansBen1Title: 'Best-in-class color fidelity',
    plansBen1Desc: 'The most faithful automatic retouch for listing interiors on the market. Wall color, exposure and overall tone align across rooms — no overexposure, no color cast, no plastic look.',
    plansBen2Title: 'Self-service recovery',
    plansBen2Desc: 'If a render does not land the first time, you do not wait for a human retoucher or a support ticket. Click a color swatch, regenerate, and the wall color swaps instantly — your delivery timeline stays yours.',
    plansBen3Title: 'Material & structure safe',
    plansBen3Desc: 'Detects wood, stone and textiles — corrects light and color without harming texture.',
    plansBen4Title: 'Fast turnaround',
    plansBen4Desc: 'Upload once and pull down the whole listing in one sitting — no overnight renders, no piece-by-piece waiting.',
    plansBen5Title: 'Transparent billing',
    plansBen5Desc: 'See an estimate up front. Only successful frames are charged. Full history is always in the billing page.',
    plansBen6Title: 'Always evolving',
    plansBen6Desc: 'We are in active development — new capabilities ship continuously and existing users upgrade automatically. You are not buying a frozen product, you are buying a tool that keeps getting better.',
    plansScenesKicker: 'How to work with us',
    plansScenesTitle: 'Three options — pick what fits',
    plansScene1Tag: 'Credit system',
    plansScene1Title: 'Pay as you go · top up anytime',
    plansScene1Desc: 'Top up flexibly using the tiers above. 1 credit = 1 photo. No local hardware — open a browser and start. Ideal for variable volume or teams that want to get moving right away.',
    plansScene1MetaLabel: 'Start from',
    plansScene1MetaValue: '$100',
    plansScene2Tag: 'Software license',
    plansScene2Title: 'One-time payment · local deployment',
    plansScene2Desc: 'Perpetual software license. Runs locally on an RTX 3090 or better. Around 3 minutes per photo, varying with output resolution. Best for studios with steady volume and strict data-locality requirements.',
    plansScene2MetaLabel: 'Hardware',
    plansScene2MetaValue: 'GPU 3090+',
    plansScene3Tag: 'Enterprise partnership',
    plansScene3Title: '$15,000 · enterprise partnership',
    plansScene3Desc: 'For teams that need long-term control and deeper customization, we provide full delivery, onboarding, and dedicated support so the service can fit into your existing business line.',
    plansScene3MetaLabel: 'One-time',
    plansScene3MetaValue: '$15,000',
    plansFaqKicker: 'FAQ',
    plansFaqTitle: 'Top-ups, usage, refunds',
    plansFaq1Q: 'Do credits expire?',
    plansFaq1A: 'No. Once credits land in your account they stay valid indefinitely.',
    plansFaq2Q: 'Am I charged for failed renders?',
    plansFaq2A: 'No. The estimated credits are for preview only. You are only billed for successfully delivered frames.',
    plansFaq3Q: 'Can I get an invoice?',
    plansFaq3A: 'Yes. Submit invoice details from the billing page after topping up — both personal and company titles are supported.',
    plansFaq4Q: 'Can I request a refund?',
    plansFaq4A: 'Yes. Refunds are handled manually by an admin after checking the order amount, delivered credits, consumed credits, refundable amount, and remaining balance.',
    plansFaq5Q: 'How do activation codes work?',
    plansFaq5A: 'Enter the code in the top-up modal. It is validated and applied automatically, and any bonus credits land with the top-up.',
    plansCtaTitle: 'Ready to keep every listing on one visual wavelength?',
    plansCtaSub: 'Create an account to try it. Your first top-up instantly earns the matching tier discount.',
    plansCtaBtn: 'Start now',
    studioLabel: 'Metrovan AI Studio'
  }
} satisfies Record<UiLocale, LandingPageCopy>;

export function getStoredLandingLocale(): UiLocale {
  if (typeof window === 'undefined') {
    return 'zh';
  }

  try {
    return window.localStorage.getItem('metrovanai_locale') === 'en' ? 'en' : 'zh';
  } catch {
    return 'zh';
  }
}
